---
title: "Geographical representation of community assembly"
output: html_notebook
---

```{r setup, message = F, warning = false}
library(dplyr)
library(purrr)
library(tidyverse)
library(tidyr)

library(sf)
```

This file uses outputs from `community_assembly.Rmd`.

```{r}
community_assembly_output = read_csv('./cache/community_assembly_all_species_result.csv')
```

```{r}
world_cities <- read_sf('../../data/third_party/world_bank_city_locations/world_bank_city_locations.shp')
names(world_cities) <- c('city_id', 'city_name', 'geometry')
world_cities = world_cities[world_cities$city_id %in% community_assembly_output$city_id,]
world_cities = right_join(world_cities, community_assembly_output)
```
```{r}
country_outlines <- read_sf('../../data/third_party/world_bank_country_outlines/world-administrative-boundaries.shp')
world_cities <- st_transform(world_cities, crs = st_crs(country_outlines))
```

```{r}
ggplot() +  
  geom_sf(data = country_outlines, aes(geometry = geometry)) +
  geom_sf(data = world_cities, aes(geometry = geometry, color = mntd_normalised), show.legend = "point") +
  theme_bw() + theme(legend.position="bottom") + scale_colour_gradient2(
  low = "red",
  mid = "yellow",
  high = "darkgreen",
  midpoint = 0.5,
  space = "Lab",
  na.value = "grey50",
  guide = "colourbar",
  aesthetics = "colour"
)
```
